language: python

sudo: false

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

install:
    - pip install -U pip
    - pip install torch==1.3.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

    # Keep track of Pyro dev branch
    - pip install https://github.com/pyro-ppl/pyro/archive/dev.zip

    - pip install .[test]
    - pip freeze

branches:
    only:
        - master

jobs:
    include:
        - python: 3.6
          script: make test
