language: python

sudo: false

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

install:
    - pip install -U pip
    - pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl

    # Keep track of Pyro dev branch
    - pip install https://github.com/pyro-ppl/pyro/archive/dev.zip

    - pip install .[test]
    - pip freeze

branches:
    only:
        - master

jobs:
    include:
        - python: 3.6
          script: make test
